In [1]:
 from president_speech.db.parquet_interpreter import read_parquet, get_parquet_full_path

In [2]:
data_path = get_parquet_full_path()

In [3]:
import pandas as pd

In [4]:
df = pd.read_parquet(data_path)

In [5]:
df.head(3)

,division_number,president,title,date,location,kind,speech_text
5368,1305368,박정희,제5대 대통령 취임식 대통령 취임사,1963.12.17,국내,취임사,"\n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ..."
5369,1305369,박정희,국회 개회식 치사,1963.12.17,국내,기념사,"존경하는 국회의장, 의원제위 그리고 내외귀빈 여러분! 오늘 이 뜻깊은 제3공화국의..."
5370,1305370,박정희,신년 메시지,1964.01.01,국내,신년사,친애하는 국내외의 동포 여러분! 혁명의 고된 시련을 겪고 민정이양으로 매듭을 지은...

In [6]:
df.index

Index([  5368,   5369,   5370,   5371,   5372,   5373,   5374,   5375,   5376,
         5377,
       ...
       102582, 102583, 102584, 102585, 102586, 102587, 102588, 102589, 102590,
       102591],
      dtype='int64', length=8771)

In [7]:
df.values[1:3]

array([[1305369, '박정희', '국회 개회식 치사', '1963.12.17', '국내', '기념사',
        ' 존경하는 국회의장, 의원제위 그리고 내외귀빈 여러분! 오늘 이 뜻깊은 제3공화국의 첫 국회 개회식에 즈음하여, 나는 먼저 지난 11월 26일에 실시된 국회의원 총선거에서 국민의 대표로서 당선의 영예를 획득하신 국회의원 여러분께 축하를 드리고 또한 이 새 국회의 앞날에 무궁한 발전이 있기를 충심으로 축원하는 바입니다. 5ㆍ16 혁명으로부터 2년 7개월만에 온 겨레의 벅찬 기대와 희망 속에 새로운 출발을 보게 되는 이 첫 국회가 국정운영의 중책을 맡고 그 역사적 개회를 보게 된 것을 나는 국민 여러분과 더불어 무한한 기쁨으로 생각하여 마지 않읍니다. 그러나 기쁨과 희망 속에 새 국회의 뜻 깊은 탄생을 경축하는 우리들은 2차의 혁명으로 이 나라 의회정치의 중단을 자초하지 않을 수 없었던 지난날을 회고, 반성하면서 오늘 이 국회 의 개회와 더불어 국민 앞에 뼈저린 반성과 새로운 결의를 가다듬지 않을 수 없을 것입니다. 실로 일천한 민주역사에서 국정의 중심을 담당하여 온 이 나라 국회는 무상한 변천과 파란을 겪어 왔던 것입니다. 건국초로부터 산적된 과제를 해결하는 데 국회는 다대한 업적을 쌓아 왔으나, 반면 헌정의 주체로서의 국회는 그 본연의 업무에만 충실하지는 않았던 것입니다. 때로는 다수당의 횡포나 불법적 개헌을 통한 1인, 1당의 항구집권을 합리화하기 위한 하나의 방편으로 전락되었으며 때로는 부질없는 정쟁과 명분없는 이합집산으로 무위무능한 국회로 변모하였던 영예롭지 못한 전통을 남긴 일조차 있었읍니다. 지난 10수년 헌정사에 나타난 우리의 경험은 이 나라 정치의 건전화를 위하여서는 대의제 민주정치의 제도적 형식과 절차에 앞서 건전한 정치도의의 확립이 절실히 요청되고 있음을 뚜렷이 입증하고 있는 것입니다. 이제 새로운 헌정복귀의 역사적 전환점에 서서, 오늘의 긴박한 우리의 현실이 지난날에 있었던 우리 헌정의 실패를 다시는 반복됨을 허용치 않을 것이 분명하다면, 민주적 질서와 원칙에 조화된 정국안정과 능률정치의 확보는 여야라는 정치적 대립의 장벽을 초월하는 공통된 기본과제라 아니할 수 없으며, 이 기본과제의 해결은 여야간의 평화로운 공존과 그에 바탕하는 정치도의의 확립이 선행되어야 함은 재삼 강조할 필요가 없을 것입니다. 그 전날 서로가 구적시하고 관용과 타협을 부정하는 극한투쟁으로 초래하였던 과거의 감정정치와 위기정치는 이 땅에서 영원히 불식되어야 할 것입니다. 정책면에서는 서로가 경쟁하면서도 국가이익이라는 공통목표에 충성하고, 「근본적인 것」에 대하여서 만은 일반적 일치를 대전제로 한다는 공익우선의 영예로운 전통과 기풍이 확립되어야 하겠으며 관용과 타협으로 그리고 이해와 설득으로 국정의 진지한 해결을 도모해 나아가야 할 것입니다. 의원 여러분! 지금 우리가 처한 냉혹한 현실을 직시할 때, 실로 우리는 새로운 각성과 결의를 굳게 하지 않을 수 없읍니다. 5ㆍ16혁명을 주동한 책임자의 한 사람으로서 나는 지난 혁명기간중 혁명정부의 몇 가지 실책을 솔직히 자인한 바 있으며 또한 시책상 미비점을 시정함에 온갖 열의를 다하여 왔읍니다. 그러나 혁명과업완수를 위한 우리들의 힘찬 노력과 헌신에도 불구하고 지난 1년간의 겹친 흉작과 민정이양이라는 과도적 전환점을 계기로 조성된 심리적 동요는 극심한 물가고를 초래하였고 근간의 경제사정은 매우 핍박한 양상을 보이고 있는 것이 우리의 실정입니다. 이 시급한 경제적 난경의 타개를 위해서는 무엇보다도 거족적인 단합과 협조가 필요하며 여야를 초월한 일치협력과 노력이 절실함을 나는 강조하지 않을 수 없읍니다. 따라서 정국의 안정과 경제의 안정, 부흥은 우리가 당면한 가장 긴박한 과제가 아닐 수 없으며 정부와 국회 의 일치된 협력으로 강력한 경제시책을 수행해 나가야 할 것이며, 또한 국민전체의 적극적인 분발, 협조가 병행되어 나가야 하겠읍니다. 이제 민정이양의 성공적 완수로서 군정의 실질적 종언과 새로운 민주적 정부의 탄생이 확정된 오늘, 이 나라 정치의 중심과제는 우리가 처한 현실적 발판 위에서 여하히 민심의 안정과 경제의 안정ㆍ부흥을 기할 것인가의 민족적 공통과제일 뿐이며, 진통에 겨웠던 과거에 집착 하여 부질없고 허황된 한탄과 비방에 주저하여서는 안될 것입니다. 지난 혁명2년여의 시책상 과오와 미비가 오늘의 시점에서 이미 초점을 잃은 정쟁의 구실로 타락하기 전에, 우리는 이 막중하였던 혁명적 시련이 우리에게 부하한 반성적 경험을 토대로 건설과 부흥과 번영의 길로 총매진하여 나가야 할 것입니다. 의원 여러분! 금반 새로이 구성된 국회에서는 여당의 안정세력확보로서 온 국민이 절실히 염원하는 정국안정의 새로운 계기가 형성되었음을 나는 매우 기쁘게 생각하는 바입니다. 이제 이 정국안정의 새로운 계기를 더욱 향상, 발전시켜 새로운 국회의 기풍 속에 정부와의 긴밀한 유대를 다짐하고, 상호이해와 협조로서 우리 앞에 산적된 당면과제를 신속히 처리해 나가는 데 우리의 모든 지혜와 역량을 총집결하여야 하겠읍니다. 제3공화국의 국회는 지난날의 국회처럼 질시와 반목 속에 정쟁에 여념이 없던 무기력한 국회가 되어서는 안될 것입니다. 여야를 막론하고 독선과 우월과 극한적 대결 등의 고루한 과거의 폐풍을 일소하고 타협과 협조 속에 「일하는 국회」가 되어야 하겠읍니다. 헌정 10수년에 걸쳐 계속된 파쟁과 부패와 혼란의 악순환만을 체험하여온 국민 여러분의 메마른 가슴속에 우리는 「존경받는 국회」와 「일하는 정부」라는 영예로운 인식을 북돋아 주고 조국재건을 위한 헌신적 참여를 촉구하여야 하겠읍니다. 오늘 새로운 포부와 결의로 넘쳐흐르는 의원 여러분의 믿음직스러운 용자는, 국정운영의 중책을 맡은 나에게 무한한 용기와 의욕을 불러일으키고, 벅찬 기대를 가진 국민 여러분의 가슴속에 새로운 희망을 안겨다 줄 것을 믿어 마지않습니다. 의원 여러분의 참다운 열성과 실천으로 반드시 이 땅에 명랑한 복지사회가 이룩될 것을 확신하면서 오늘의 성스러운 국회 개회식의 치사를 대할까 합니다. 끝으로 여러분의 건강과 행복을 진심으로 기원하는 바입니다. '],
       [1305370, '박정희', '신년 메시지', '1964.01.01', '국내', '신년사',
        ' 친애하는 국내외의 동포 여러분! 혁명의 고된 시련을 겪고 민정이양으로 매듭을 지은 다난하였던 해 계묘년을 보내고, 우리들 앞날에 새로운 희망과 광명을 안겨다 줄 갑신년의 새 아침을 맞이하게 된 것을 국민 여러분과 더불어 충심으로 경하해 마지않습니다. 돌이켜 보건대 지난해는 혁명이 이룩하려고 하였던 많은 과업이 뜻하지 않은 겹친 천재와 정치적 동요로 말미암아 다소의 차질을 불가피하게 하였던 「시련의 해」인 동시에, 군정을 종식시키고 새 공화국과 새로운 민주적 정부를 성공리에 수립한 뜻 깊은 해였읍니다. 나는 오늘 송구영신의 새 아침을 맞이함에 앞서 지난 1년 동안 국민 여러분들이 갖가지 불편과 고난을 참고 이겨낸 크나큰 노고를 높이 치하하고, 또한 그 불우한 역경 속에서도 민정이양을 깨끗하고 모범적인 분위기 속에 완수하여 우리들의 민주역량을 내외에 과시한 자랑스러운 업적에 대하여 심심한 사의를 표하는 바입니다. 이제 제3공화국에서 국정운영의 중책을 맞게 된 나는 희망찬 새해와 더불어 우리가 당면한 몇 가지 시급한 과제를 국민 앞에 제시하고 이를 해결해 나가기 위한 우리들의 한결같은 자세와 굳은 결의를 가다듬고자 하는 바입니다. 우선 여야 모든 정치세력의 일치된 협조로서 새로운 정치기풍 속에 「능률 있는 정치」를 구현시켜 나감으로써 정국의 안정을 기하는 한편 제반정치적 결정을 신속히 반영, 시행할 수 있는 「행정의 능률」을 확보시켜야 하겠읍니다. 정부와 국회 그리고 모든 정부기관상호간의 유기적 협조와 조정으로서 국민여러분의 의사를 정확하게 그리고 효과적으로 국정에 반영토록 할 수 있는 넓은 통로를 마련하여 놓을 것입니다. 다음으로 시급한 것은 경제를 안정키고 하루속히 발전의 궤도 위에 올려놓는 일입니다. 새 정부는 현재 우리가 겪고 있는 물가고와 제반경제적 난경을 타개하기 위하여 모든 중지와 역량을 모아 시급한 해결에 임할 것이며 5개년경제계획을 합리적으로 무리 없이 꾸준히 추진해 나가겠읍니다. 심한 물가고에 시달리는 국민 여러분의 안타까움을 덜어 주고 생활향상의 목마른 기대를 하루 바삐 충족시켜 드리기 위해 새 정부는 밤낮을 가리지 않고 모든 열의와 역량을 다할 것을 굳게 다짐해 두는 바입니다. 친애하는 국민 여러분! 새 정부는 그 출발에 즈음하여 국민 앞에 많은 약속을 한 바 있읍니다. 그러나, 우리가 명심하지 않을 수 없는 것은 건설과 번영을 위한 전진 앞에는 결코 요행이나 기적이 쉽사리 이루어질 수 없다는 뼈저린 역사적 교훈일 것입니다. 새 정부는 결코 요행을 바라지 않을 것이며 또한 국민 여러분은 가만히 앉아서 기적을 고대하지는 말아야 할 것입니다. 국정에 임한 새 정부의 자세는 한마디로 「성실한 일군」이 되겠다는 것입니다. 국민과 더불어 호흡하고 솔선하여 실천하는 「믿을 수 있는 정부」가 될 것을 국민 앞에 약속해 드립니다. 새 공화국의 앞날에 부정과 부패는 철저히 발본색원될 것이며 공무원의 기강은 내실적으로 재확립될 것입니다. 깨끗하고 성실을 다하여 능률적으로 일하는 공무원의 기풍을 수립하기 위하여 나는 모든 조치와 철저한 감시를 부단히 계속코자 합니다. 허망한 약속과 구호에 앞서 새 정부는 하나하나 착실히 실천해 나가는 믿음직스러운 자세를 견지해 나갈 것을 뚜렷이 밝혀 두는 바입니다. 내가 제창한 바 있는 대혁신운동은 바로 이러한 정부 스스로의 자숙자계, 공무원의 정신혁명에서 시발되어야 할 것으로 믿고 있읍니다. 친애하는 국민 여러분! 지금 조국이 처한 냉혹한 현실과 제반여건하에서 우리의 당면과제가 해결되어나가고 우리의 꿈이 실현되기 위하여서는 정부의 일방적 세력만으로는 도저히 불가능함을 우리는 깊이 깨달아야 하겠읍니다. 국민 여러분의 적극적 참여와 자발적 협조 없이 우리가 당면한 시급한 과제는 쉽사리 해결될 수 없는 것입니다. 불만족스러운 우리의 현실과 고달픈 우리들 생활난에 우리는 실의와 체념으로 비관하지 말고 이 가혹한 시련을 참고 견디며 끝까지 이겨 나가야 하겠읍니다.우리 다시금 함께 일어서서 부지런히 일하고 서로가 협조해 나가야 할 때가 온 것입니다.우리의 생활주변에서 허영과 낭비의 퇴폐한 기운을 말끔히 씻어 버리고 내핍과 근면 속에 검소한 생활기풍을 세워 나갈 것을 국민 여러분에게 호소하는 바입니다. 친애하는 국민 여러분! 정부의 시책을 이해하고 또한 협조하는 건실한 태도와 함께 「근면한 생활인」의 자세를 살려나가는 한 복지사회를 지향하는 우리의 노력과 분발은 반드시 그리고 하루 속히 결실될 날이 올 것을 나는 확신해 마지않습니다. 새 정부를 믿고 모든 협조를 아끼지 맙시다. 각자의 생활분야에서 땀 흘려 일하고 끈기 있게 그리고 착실히 하나씩 쌓아 올라갑시다. 「일하는 정부」와 「일하는 국민」의 일치단합으로써 희망찬 새해를 발전과 번영의 발판으로 만들어 나갑시다. 끝으로 갑진년의 새 아침을 맞이하여 해외에 계시는 모든 동포에게 나는 국내동포와 더불어 새해 인사와 격려를 보내 마지않으며 특히 공산학정하에서 신음하는 북한동포의 불운한 처지를 슬퍼하면서 그들을 구원하려는 우리들의 결의를 새로이 하는 한편 국내외 우리 모든 동포의 앞날에 만복이 깃들기를 빌고 하나님의 은총과 가호가 항상 우리와 같이 하시기를 기원하는 바입니다.']],
      dtype=object)

In [8]:
type(df)

pandas.core.frame.DataFrame

df.columns

In [10]:
df.columns

Index(['division_number', 'president', 'title', 'date', 'location', 'kind',
       'speech_text'],
      dtype='object')

In [11]:
df.T

,5368,5369,5370,5371,5372,5373,5374,5375,5376,5377,...,102582,102583,102584,102585,102586,102587,102588,102589,102590,102591
division_number,1305368,1305369,1305370,1305371,1305372,1305373,1305374,1305375,1305376,1305377,...,1401982,1401983,1401984,1401985,1401986,1401987,1401988,1401989,1401990,1401991
president,박정희,박정희,박정희,박정희,박정희,박정희,박정희,박정희,박정희,박정희,...,문재인,문재인,문재인,문재인,문재인,문재인,문재인,문재인,문재인,문재인
title,제5대 대통령 취임식 대통령 취임사,국회 개회식 치사,신년 메시지,신년 시무식에 즈음한 담화문,고급공무원에게 보내는 서신,여당 국회의원에게 보내는 서신,1964년 대통령 연두교서,자유의 날 10주년에 즈음한 메시지,지방장관회의 유시,제45회 3·1절 경축사,...,제9회 국무회의,수석·보좌관회의,제11회 국무회의,수석·보좌관회의,제14회 국무회의,수석·보좌관회의,제16회 국무회의,수석·보좌관회의,수석·보좌관회의,제18회 국무회의
date,1963.12.17,1963.12.17,1964.01.01,1964,1964.01.04,1964.01.04,1964.01.10,1964.01.23,1964,1964.03.01,...,2021.03.02,2021.03.15,2021.03.16,2021.03.22,2021.03.30,2021.04.05,2021.04.13,2021.04.19,2021.04.26,2021.04.27
location,국내,국내,국내,국내,국내,국내,국내,국내,국내,국내,...,국내,국내,국내,국내,국내,국내,국내,국내,국내,국내
kind,취임사,기념사,신년사,성명/담화문,기념사,기념사,국회연설,기념사,기념사,기념사,...,회의,회의,회의,회의,회의,회의,회의,회의,회의,회의
speech_text,"\n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ...","존경하는 국회의장, 의원제위 그리고 내외귀빈 여러분! 오늘 이 뜻깊은 제3공화국의...",친애하는 국내외의 동포 여러분! 혁명의 고된 시련을 겪고 민정이양으로 매듭을 지은...,친애하는 전국의 공무원 여러분! 민족 역사 위에 격동과 시련의 해로 길이 기록될 계...,"청 감갑진년의 새아침을 맞이하여 귀하와 귀하의 가정에 만복이 깃들기를 빌며, 새해에...",희망찬 갑진년의 새아침을 맞이하여 귀하와 귀하의 가정에 만복이 깃들기를 삼가 빌며 ...,"존경하는 국회의장, 그리고 국회의원 여러분! \n\n\n국회가 개원된 이래 난국타개...",친애하는 반공애국청년 여러분! 그리고 사랑하는 동포 여러분! 오늘 「자유의 날」 제...,친애하는 지방장관 여러분! 제3공화국 수립이후 처음으로 갖게 되는 이 뜻 깊은 지방...,오늘 뜻 깊은 제45회 3.1절을 맞이하여 선열의 영혼이 지켜보는 가운데 기념식전을...,...,백신 접종이 순조롭게 진행되며 일상 회복을 위한 대장정의 첫발을 내디뎠습니다. 이제...,우리 정부는 여러 분야에서 적폐청산을 이루어 왔으나 부동산 적폐의 청산까지는 엄두를...,우리 정부 들어 제정된 의미 있는 법안들이 많습니다. 오늘 공포하는 「행정기본법」도...,아스트라제네카(AstraZeneca) 백신의 안전성과 효과가 국제적으로 재확인되었습...,우리 경제가 빠르고 강하게 회복하고 있습니다. 여러 국제기구들이 올해 우리나라의 경...,우리가 코로나19 이전으로 얼마나 빨리 돌아갈 수 있는지 여부는 오로지 방역과 백신...,"정부는 국민께 무한책임을 진다는 자세로 흔들림 없이 국정에 임해야 합니다.방역도, ...",우리 정부 임기 마지막 날까지 흔들림 없이 국민과 역사가 부여한 책무를 다하자는 다...,코로나19와 같은 감염병의 세계적 대유행은 어느 한 나라가 자국의 문제를 해결한다고...,오늘 한국은행이 발표한 1분기 GDP 속보치에 따르면 우리 경제는 올해 1분기에 이...

In [12]:
df.sort_values(by='president').head()

,division_number,president,title,date,location,kind,speech_text
8763,1308731,김대중,새천년준비위원 위촉장 수여 및 오찬 말씀(새천년에 가장 중요한 것은 의식개혁),1999.04.12,국내,기념사,여러분께서 이번에 새천년을 앞두고 우리의 운명을 생각하는 막중한 대임을 맡게 되었습...
8941,1308909,김대중,제78회 어린이날 축하 메시지(꿈을 가진 사람만이 내일을 만듭니다),2000.05.05,국내,기념사,사랑하는 어린이 여러분 일흔여덟번째 어린이날을 축하합니다. 오늘은 새천년의 첫 번째...
8942,1308910,김대중,알레만 니카라과 대통령 내외를 위한 만찬연설(니카라과는 새천년 공동번영의 동반자),2000.05.15,국내,환영사,"알레만 니카라과 대통령 각하 내외분,그리고 내외 귀빈 여러분! 먼 여로를 마다치 않..."
8943,1308911,김대중,미국 경제전략연구소(ESI) 포럼 개막식 기조연설(21세기 글로벌화의 혜택과 대가),2000.05.15,국제,성명/담화문,\r\n \r\n대통령 기조 연설문 \n\r\n< 모두말씀 > \n\r\n친애하는 ...
8944,1308912,김대중,ASEM 컨벤션센터 개관식연설(개방형 신통상국가를 열어갑시다),2000.05.16,국내,기타,"\r\n \r\n존경하는 국민 여러분,\n\r\n그리고 이 자리에 참석하신 내외귀빈..."

In [13]:
df['president'].head(3)

5368    박정희
5369    박정희
5370    박정희
Name: president, dtype: object

In [14]:
df[0:3]

,division_number,president,title,date,location,kind,speech_text
5368,1305368,박정희,제5대 대통령 취임식 대통령 취임사,1963.12.17,국내,취임사,"\n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ..."
5369,1305369,박정희,국회 개회식 치사,1963.12.17,국내,기념사,"존경하는 국회의장, 의원제위 그리고 내외귀빈 여러분! 오늘 이 뜻깊은 제3공화국의..."
5370,1305370,박정희,신년 메시지,1964.01.01,국내,신년사,친애하는 국내외의 동포 여러분! 혁명의 고된 시련을 겪고 민정이양으로 매듭을 지은...

In [16]:
df.iloc[0]

division_number                                              1305368
president                                                        박정희
title                                            제5대 대통령 취임식 대통령 취임사
date                                                      1963.12.17
location                                                          국내
kind                                                             취임사
speech_text        \n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ...
Name: 5368, dtype: object

In [17]:
df.iloc[0,0]

1305368

In [21]:
df.iloc[0:2,0:3]

      division_number president                title
5368          1305368       박정희  제5대 대통령 취임식 대통령 취임사
5369          1305369       박정희            국회 개회식 치사

In [22]:
df.iat[0,1]

'박정희'

In [25]:
df[df['president'].isin(['노무현', '박정희'])]

,division_number,president,title,date,location,kind,speech_text
5368,1305368,박정희,제5대 대통령 취임식 대통령 취임사,1963.12.17,국내,취임사,"\n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ..."
5369,1305369,박정희,국회 개회식 치사,1963.12.17,국내,기념사,"존경하는 국회의장, 의원제위 그리고 내외귀빈 여러분! 오늘 이 뜻깊은 제3공화국의..."
5370,1305370,박정희,신년 메시지,1964.01.01,국내,신년사,친애하는 국내외의 동포 여러분! 혁명의 고된 시련을 겪고 민정이양으로 매듭을 지은...
5371,1305371,박정희,신년 시무식에 즈음한 담화문,1964,국내,성명/담화문,친애하는 전국의 공무원 여러분! 민족 역사 위에 격동과 시련의 해로 길이 기록될 계...
5372,1305372,박정희,고급공무원에게 보내는 서신,1964.01.04,국내,기념사,"청 감갑진년의 새아침을 맞이하여 귀하와 귀하의 가정에 만복이 깃들기를 빌며, 새해에..."
...,...,...,...,...,...,...,...
10156,1310124,노무현,2008년 신년사,2008.01.01,국내,신년사,"국민 여러분,2008년 새해가 밝았습니다. 올 한 해 뜻하시는 일 모두 이루시기 바..."
10157,1310125,노무현,울산 국민보도연맹사건 희생자 추모식에 보내는 메시지,2008.01.24,국내,기념사,"존경하는 울산시민 여러분,그리고 국민보도연맹사건 유가족 여러분,58년 전, 국민보도..."
10158,1310126,노무현,정부조직개편안 관련 기자회견,2008.01.28,국내,성명/담화문,"존경하는 국민 여러분,\r\n \r\n저는 오늘, 차기 정부 인수위의 정부조직개편안..."
10362,1310330,박정희,기자회견,1969.04.25,국내,성명/담화문,질문 : 지난 1/4분기 실적 평가와 관련해서 금년도 목표 달성의 전망에 대하여 말...
10468,1310436,박정희,달에 보내는 멧시지 (아폴로 11호),1969.07.15,국내,성명/담화문,아폴로 11호에 의한 달 착륙은 온 인류에게 인간의 꿈을 실현시켜주고 인류사에 새로...

In [28]:
df[df['president'].isin(['박정희', '노무현'])].head(3)

,division_number,president,title,date,location,kind,speech_text
5368,1305368,박정희,제5대 대통령 취임식 대통령 취임사,1963.12.17,국내,취임사,"\n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ..."
5369,1305369,박정희,국회 개회식 치사,1963.12.17,국내,기념사,"존경하는 국회의장, 의원제위 그리고 내외귀빈 여러분! 오늘 이 뜻깊은 제3공화국의..."
5370,1305370,박정희,신년 메시지,1964.01.01,국내,신년사,친애하는 국내외의 동포 여러분! 혁명의 고된 시련을 겪고 민정이양으로 매듭을 지은...

In [29]:
df[df['president'] == '노무현'].head(1)

,division_number,president,title,date,location,kind,speech_text
9379,1309347,노무현,제16 대 대통령 취임사,2003.02.25,국내,취임사,존경하는 국민 여러분.오늘 저는 대한민국의 제16대 대통령에 취임하기 위해 이 자리...

In [38]:
df[df['speech_text'].str.contains("자유")]

,division_number,president,title,date,location,kind,speech_text
5368,1305368,박정희,제5대 대통령 취임식 대통령 취임사,1963.12.17,국내,취임사,"\n\n\n단군성조가 천혜의 이 강토 위에 국기를 닦으신지 반만년, 연면히 이어온 ..."
5374,1305374,박정희,1964년 대통령 연두교서,1964.01.10,국내,국회연설,"존경하는 국회의장, 그리고 국회의원 여러분! \n\n\n국회가 개원된 이래 난국타개..."
5375,1305375,박정희,자유의 날 10주년에 즈음한 메시지,1964.01.23,국내,기념사,친애하는 반공애국청년 여러분! 그리고 사랑하는 동포 여러분! 오늘 「자유의 날」 제...
5377,1305377,박정희,제45회 3·1절 경축사,1964.03.01,국내,기념사,오늘 뜻 깊은 제45회 3.1절을 맞이하여 선열의 영혼이 지켜보는 가운데 기념식전을...
5379,1305379,박정희,한·일회담에 관한 특별담화문,1964.03.26,국내,성명/담화문,"친애하는 국민 여러분! \n\n\n지난 며칠 동안 한, 일회담문제로 일부 학생들이 ..."
...,...,...,...,...,...,...,...
102534,1401934,문재인,제74주년 광복절 경축사,2019.08.15,국내,기념사,"존경하는 국민 여러분,독립유공자와 유가족 여러분,재외ㆍ해외동포 여러분,3.1독립운동..."
102535,1401935,문재인,제74차 유엔 총회 기조연설,2019.09.24,국내,성명/담화문,"유엔과 회원국들의 헌신으로 세계의 많은 문제들이 해결되고, 평화를위한 노력들이 결실..."
102546,1401946,문재인,제37회 국무회의,2020.07.21,국내,회의,한국판 뉴딜은 국내 공간적으로는 수도권 중심에서 지역 중심으로 국가발전의 축을 이동...
102550,1401950,문재인,수석·보좌관회의,2020.08.24,국내,회의,"국민 여러분, 코로나19가 발생한 이후 우리나라에서는 지금이 최대의 위기입니다. 우..."
102556,1401956,문재인,제48회 국무회의,2020.09.22,국내,회의,코로나19 재확산의 중대 고비를 온 국민이 힘을 모아 이겨내고 있습니다. 일일 국내...

In [48]:
# https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains
df['speech_text'].str.contains("올림픽")

5368      False
5369      False
5370      False
5371      False
5372      False
          ...
102587    False
102588    False
102589    False
102590    False
102591    False
Name: speech_text, Length: 8771, dtype: bool

In [43]:
f_df.groupy("president").size().reset_index(name="count")

AttributeError: 'DataFrame' object has no attribute 'groupy'

In [49]:
# https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains
f_df = df[df['speech_text'].str.contains("올림픽", case=False)]

In [50]:
f_df.head(1)

,division_number,president,title,date,location,kind,speech_text
5374,1305374,박정희,1964년 대통령 연두교서,1964.01.10,국내,국회연설,"존경하는 국회의장, 그리고 국회의원 여러분! \n\n\n국회가 개원된 이래 난국타개..."

In [51]:
rdf = f_df.groupby("president").size().reset_index(name="count")

In [52]:
print(rdf)

  president  count
0       김대중     40
1       김영삼     32
2       노무현     32
3       노태우    292
4       문재인    161
5       박근혜     14
6       박정희     29
7       이명박    107
8       전두환    165
9       최규하      2

In [55]:
rdf.sort_values(by='count', ascending=False)

  president  count
3       노태우    292
8       전두환    165
4       문재인    161
7       이명박    107
0       김대중     40
1       김영삼     32
2       노무현     32
6       박정희     29
5       박근혜     14
9       최규하      2